import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { useSession, SessionProvider } from 'next-auth/react';

// ANT

import { AntdRegistry } from '@ant-design/nextjs-registry';



export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
  session
}: Readonly<{ children: React.ReactNode, session: never }>) {

  return (
    <html lang="en" style={{ height: "100%", width: "100%" }} >
      <body style={{ height: "100%", width: "100%" }}>
        <AntdRegistry>
            <SessionProvider session={session}>
              <TRPCReactProvider>
            {children}
            </TRPCReactProvider>
            </SessionProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
